/* ═══════════════════════════════════════
   GES — data.js
   Complete missile arsenal database
   Real specs, multiple nations
   ═══════════════════════════════════════ */

const MISSILE_DB = [
  // ── RUSSIA ──────────────────────────────
  {
    id: 'R-Kalibr',
    name: 'Kalibr (3M-14)',
    natoCode: 'SS-N-30A Sagaris',
    country: 'russia', flag: '🇷🇺',
    type: 'cruise',
    range: 2500, // km
    speed: 240, // m/s (~Mach 0.7)
    speedMach: 0.7,
    altitude: 50, // m cruise altitude
    warhead: '450 kg HE o nuclear táctico',
    guidance: 'INS + TERCOM + GLONASS + Optical',
    length: 8.2, diameter: 0.53,
    launchPlatform: ['Submarino', 'Buque superficie', 'Tierra'],
    CEP: 3, // m circular error probable
    inService: 2012,
    status: 'active',
    uses: 'Ataques de precisión larga distancia. Amplio uso en conflicto Ucrania desde 2022.',
    color: '#FF2040',
    tags: ['convencional', 'naval', 'tierra', 'precisión'],
  },
  {
    id: 'R-Iskander',
    name: 'Iskander-M (9K720)',
    natoCode: 'SS-26 Stone',
    country: 'russia', flag: '🇷🇺',
    type: 'ballistic',
    range: 500,
    speed: 2100, // m/s
    speedMach: 6.0,
    altitude: 50000,
    warhead: '480–700 kg (HE, cluster, nuclear)',
    guidance: 'INS + GLONASS + TERCOM + EO homing',
    length: 7.3, diameter: 0.92,
    launchPlatform: ['Lanzador TEL terrestre'],
    CEP: 5,
    inService: 2006,
    status: 'active',
    uses: 'Misil balístico táctico de alta precisión. Capacidad de maniobra durante vuelo para evasión de interceptores.',
    color: '#FF2040',
    tags: ['balístico', 'táctico', 'dual-capaz'],
  },
  {
    id: 'R-Kinzhal',
    name: 'Kh-47M2 Kinzhal',
    natoCode: 'AS-24 Killjoy',
    country: 'russia', flag: '🇷🇺',
    type: 'hypersonic',
    range: 2000,
    speed: 3500, // m/s
    speedMach: 10,
    altitude: 20000,
    warhead: '480 kg convencional o nuclear',
    guidance: 'INS + GLONASS + Activo terminal',
    length: 8.0, diameter: 1.0,
    launchPlatform: ['MiG-31K', 'Tu-22M3', 'Su-57 (en desarrollo)'],
    CEP: 1,
    inService: 2017,
    status: 'active',
    uses: 'Misil balístico aerolanzado hipersónico. Imposible de interceptar con sistemas actuales. Usado en Ucrania.',
    color: '#00F5D4',
    tags: ['hipersónico', 'aire-suelo', 'anti-naval'],
  },
  {
    id: 'R-Kh101',
    name: 'Kh-101 / Kh-102',
    natoCode: 'AS-23A Kodiak',
    country: 'russia', flag: '🇷🇺',
    type: 'cruise',
    range: 2800,
    speed: 190, // m/s
    speedMach: 0.55,
    altitude: 30,
    warhead: '400 kg HE (Kh-101) / Nuclear 250kt (Kh-102)',
    guidance: 'INS + TERCOM + DSMAC + GLONASS',
    length: 7.45, diameter: 0.74,
    launchPlatform: ['Tu-95MS', 'Tu-160', 'Tu-22M3'],
    CEP: 10,
    inService: 2012,
    status: 'active',
    uses: 'Misil de crucero estratégico de largo alcance. Principal arma de ataque estratégico ruso.',
    color: '#FF8C00',
    tags: ['estratégico', 'aire-suelo', 'dual-capaz'],
  },
  {
    id: 'R-Onyx',
    name: 'P-800 Onyx (Yakhont)',
    natoCode: 'SS-N-26 Strobile',
    country: 'russia', flag: '🇷🇺',
    type: 'cruise',
    range: 600,
    speed: 750, // m/s
    speedMach: 2.2,
    altitude: 10,
    warhead: '250 kg HE penetrador',
    guidance: 'INS + radar activo terminal',
    length: 8.9, diameter: 0.67,
    launchPlatform: ['Submarino', 'Superficie', 'Tierra (Bastion-P)', 'Avión'],
    CEP: 1.5,
    inService: 2002,
    status: 'active',
    uses: 'Misil anti-naval y ataque de superficie supersónico. Exportado como BrahMos (India-Rusia).',
    color: '#FF8C00',
    tags: ['anti-naval', 'supersónico', 'multipropósito'],
  },
  {
    id: 'R-Sarmat',
    name: 'RS-28 Sarmat',
    natoCode: 'SS-X-30 Satan 2',
    country: 'russia', flag: '🇷🇺',
    type: 'ballistic',
    range: 18000,
    speed: 7000,
    speedMach: 20,
    altitude: 1200000,
    warhead: '10–15 cabezas MIRV (hasta 10MT cada una)',
    guidance: 'INS + GLONASS + ASTRO',
    length: 35.5, diameter: 3.0,
    launchPlatform: ['Silo subterráneo'],
    CEP: 10,
    inService: 2023,
    status: 'active',
    uses: 'ICBM de nueva generación. Puede atacar vía Polo Norte o Polo Sur. Incluye planeadores hipersónicos Avangard.',
    color: '#FF2040',
    tags: ['ICBM', 'nuclear', 'estratégico', 'MIRV'],
  },
  {
    id: 'R-Avangard',
    name: 'Avangard (Yu-71)',
    natoCode: 'SS-19 Mod.4',
    country: 'russia', flag: '🇷🇺',
    type: 'hypersonic',
    range: 6000,
    speed: 9600, // m/s
    speedMach: 27,
    altitude: 80000,
    warhead: 'Nuclear 2MT',
    guidance: 'INS + GLONASS + Corrección autónoma',
    length: 5.4, diameter: 0.9,
    launchPlatform: ['UR-100NUTTH', 'RS-28 Sarmat'],
    CEP: 1,
    inService: 2019,
    status: 'active',
    uses: 'Vehículo de planeo hipersónico. Maniobra a Mach 27. Invulnerable a todos los sistemas de defensa antimisiles actuales.',
    color: '#00F5D4',
    tags: ['hipersónico', 'HGV', 'nuclear', 'invulnerable'],
  },

  // ── USA ─────────────────────────────────
  {
    id: 'US-Tomahawk',
    name: 'BGM-109 Tomahawk',
    natoCode: '—',
    country: 'usa', flag: '🇺🇸',
    type: 'cruise',
    range: 2500,
    speed: 244, // m/s
    speedMach: 0.72,
    altitude: 20,
    warhead: '450 kg HE / penetrador',
    guidance: 'INS + TERCOM + DSMAC + GPS',
    length: 5.56, diameter: 0.52,
    launchPlatform: ['Submarino (VLS)', 'Destructor/Crucero', 'Lanzador tierra'],
    CEP: 5,
    inService: 1983,
    status: 'active',
    uses: 'Misil de crucero estándar de EE.UU. Más de 2.300 disparados en combate. Block IV con reorientación en vuelo.',
    color: '#0080FF',
    tags: ['convencional', 'naval', 'precisión', 'batalla-probado'],
  },
  {
    id: 'US-JASSM',
    name: 'AGM-158B JASSM-ER',
    natoCode: '—',
    country: 'usa', flag: '🇺🇸',
    type: 'cruise',
    range: 925,
    speed: 280,
    speedMach: 0.82,
    altitude: 30,
    warhead: '450 kg J-1000 penetrador',
    guidance: 'INS + GPS + IIR homing',
    length: 4.27, diameter: 0.55,
    launchPlatform: ['F-15E', 'F-16', 'B-1B', 'B-52', 'F/A-18', 'F-35 (LRASM)'],
    CEP: 1,
    inService: 2014,
    status: 'active',
    uses: 'Misil de ataque furtivo de largo alcance. Firma RCS muy baja. Usado por USAF y aliados.',
    color: '#0080FF',
    tags: ['stealth', 'aire-suelo', 'precisión'],
  },
  {
    id: 'US-Minuteman',
    name: 'LGM-30G Minuteman III',
    natoCode: '—',
    country: 'usa', flag: '🇺🇸',
    type: 'ballistic',
    range: 13000,
    speed: 7000,
    speedMach: 20,
    altitude: 1120000,
    warhead: '1–3 MIRV W87 (300kt c/u)',
    guidance: 'INS + AIRS',
    length: 18.2, diameter: 1.67,
    launchPlatform: ['Silo LGM-30'],
    CEP: 120,
    inService: 1970,
    status: 'active',
    uses: 'Componente ICBM de la tríada nuclear estadounidense. 400 en servicio activo.',
    color: '#0080FF',
    tags: ['ICBM', 'nuclear', 'MIRV', 'tríada'],
  },
  {
    id: 'US-HIMARS-ATACMS',
    name: 'MGM-140 ATACMS',
    natoCode: '—',
    country: 'usa', flag: '🇺🇸',
    type: 'ballistic',
    range: 300,
    speed: 1500,
    speedMach: 4.3,
    altitude: 50000,
    warhead: '227 kg HE (560 submuniciones o unitaria)',
    guidance: 'INS + GPS',
    length: 3.98, diameter: 0.61,
    launchPlatform: ['HIMARS', 'M270 MLRS'],
    CEP: 10,
    inService: 1991,
    status: 'active',
    uses: 'Misil balístico táctico de ataque al suelo. Suministrado a Ucrania. Alta efectividad contra depósitos y aeródromos.',
    color: '#0080FF',
    tags: ['táctico', 'HIMARS', 'Ucrania'],
  },

  // ── CHINA ───────────────────────────────
  {
    id: 'CN-DF21D',
    name: 'DF-21D (CSS-5 Mod-4)',
    natoCode: 'CSS-5 Mod-4',
    country: 'china', flag: '🇨🇳',
    type: 'ballistic',
    range: 1700,
    speed: 3000,
    speedMach: 8.8,
    altitude: 180000,
    warhead: '600 kg manobrable anti-naval',
    guidance: 'INS + BeiDou + Radar terminal activo',
    length: 10.7, diameter: 1.4,
    launchPlatform: ['TEL móvil terrestre'],
    CEP: 20,
    inService: 2010,
    status: 'active',
    uses: 'Primer misil balístico anti-naval del mundo. Diseñado para hundir portaaviones. Cambia las reglas en el Pacífico.',
    color: '#F5E642',
    tags: ['anti-naval', 'anti-portaaviones', 'estratégico'],
  },
  {
    id: 'CN-DF41',
    name: 'DF-41 (CSS-X-20)',
    natoCode: 'CSS-X-20',
    country: 'china', flag: '🇨🇳',
    type: 'ballistic',
    range: 14000,
    speed: 7000,
    speedMach: 20,
    altitude: 1200000,
    warhead: '10 MIRV (hasta 150kt c/u)',
    guidance: 'INS + BeiDou + astro-inercial',
    length: 21.0, diameter: 2.25,
    launchPlatform: ['Silo', 'TEL móvil', 'Ferroviario'],
    CEP: 100,
    inService: 2017,
    status: 'active',
    uses: 'ICBM más moderno de China. 10 cabezas MIRV. Capaz de atacar cualquier punto del territorio de EE.UU. en 30 min.',
    color: '#F5E642',
    tags: ['ICBM', 'MIRV', 'nuclear', 'estratégico'],
  },
  {
    id: 'CN-DF17',
    name: 'DF-17 + HGV DF-ZF',
    natoCode: 'CSS-22',
    country: 'china', flag: '🇨🇳',
    type: 'hypersonic',
    range: 2500,
    speed: 7000,
    speedMach: 10,
    altitude: 60000,
    warhead: 'HGV convencional o nuclear',
    guidance: 'INS + BeiDou + Autónoma terminal',
    length: 11.0, diameter: 1.4,
    launchPlatform: ['TEL móvil terrestre'],
    CEP: 3,
    inService: 2019,
    status: 'active',
    uses: 'Sistema hipersónico táctico-estratégico con planeador DF-ZF. Presentado públicamente en desfile 2019. Alto nivel de preocupación en Pentagon.',
    color: '#00F5D4',
    tags: ['hipersónico', 'HGV', 'dual-capaz'],
  },
  {
    id: 'CN-YJ18',
    name: 'YJ-18 (CM-302)',
    natoCode: 'CSS-N-13',
    country: 'china', flag: '🇨🇳',
    type: 'cruise',
    range: 540,
    speed: 1000, // terminal sprint
    speedMach: 3.0,
    altitude: 10,
    warhead: '300 kg penetrador',
    guidance: 'INS + activo radar terminal',
    length: 6.0, diameter: 0.54,
    launchPlatform: ['Submarino', 'Fragata/Destructor'],
    CEP: 5,
    inService: 2015,
    status: 'active',
    uses: 'Misil anti-naval y ataque tierra chino. Sprint supersónico terminal difícil de interceptar.',
    color: '#F5E642',
    tags: ['anti-naval', 'naval', 'supersónico terminal'],
  },

  // ── NORTH KOREA ─────────────────────────
  {
    id: 'NK-Hwasong17',
    name: 'Hwasong-17',
    natoCode: 'KN-28',
    country: 'nkorea', flag: '🇰🇵',
    type: 'ballistic',
    range: 15000,
    speed: 7200,
    speedMach: 21,
    altitude: 6200000, // lanzamiento lofted
    warhead: 'MIRV estimado hasta 4 cabezas (no confirmado)',
    guidance: 'INS',
    length: 25.0, diameter: 2.5,
    launchPlatform: ['TEL 22 ejes'],
    CEP: 500,
    inService: 2022,
    status: 'active',
    uses: 'El ICBM más grande del mundo. Capaz de alcanzar cualquier ciudad de EE.UU. Probado múltiples veces desde 2022.',
    color: '#FF0080',
    tags: ['ICBM', 'nuclear', 'estratégico', 'test-frecuente'],
  },
  {
    id: 'NK-Hwasong15',
    name: 'Hwasong-15',
    natoCode: 'KN-22',
    country: 'nkorea', flag: '🇰🇵',
    type: 'ballistic',
    range: 13000,
    speed: 6500,
    speedMach: 19,
    altitude: 4475000,
    warhead: 'Nuclear estimado (no confirmado)',
    guidance: 'INS',
    length: 22.0, diameter: 2.4,
    launchPlatform: ['TEL 18 ejes'],
    CEP: 800,
    inService: 2017,
    status: 'active',
    uses: 'ICBM que pone todo EE.UU. en rango. Probado noviembre 2017.',
    color: '#FF0080',
    tags: ['ICBM', 'nuclear', 'provocación'],
  },
  {
    id: 'NK-KN23',
    name: 'KN-23',
    natoCode: 'KN-23',
    country: 'nkorea', flag: '🇰🇵',
    type: 'ballistic',
    range: 690,
    speed: 2300,
    speedMach: 6.7,
    altitude: 60000,
    warhead: 'Convencional o táctico nuclear',
    guidance: 'INS + activo terminal',
    length: 7.5, diameter: 0.9,
    launchPlatform: ['TEL', 'Silo'],
    CEP: 30,
    inService: 2019,
    status: 'active',
    uses: 'Versión norcoreana del Iskander. Maniobra en vuelo. Suministrado a Rusia para uso en Ucrania.',
    color: '#FF0080',
    tags: ['táctico', 'Iskander-K', 'exportado a Rusia'],
  },

  // ── IRAN ─────────────────────────────────
  {
    id: 'IR-Shahab3',
    name: 'Shahab-3 / Ghadr',
    natoCode: 'CSS-8 Variant',
    country: 'iran', flag: '🇮🇷',
    type: 'ballistic',
    range: 1300,
    speed: 2500,
    speedMach: 7.3,
    altitude: 200000,
    warhead: '760–1000 kg HE o CBR',
    guidance: 'INS',
    length: 16.0, diameter: 1.25,
    launchPlatform: ['TEL terrestre'],
    CEP: 190,
    inService: 2003,
    status: 'active',
    uses: 'Principal misil balístico iraní de alcance medio. Puede alcanzar Israel. Base del programa balístico iraní.',
    color: '#FF8C00',
    tags: ['MRBM', 'regional', 'Israel-range'],
  },
  {
    id: 'IR-Fattah',
    name: 'Fattah-1',
    natoCode: '—',
    country: 'iran', flag: '🇮🇷',
    type: 'hypersonic',
    range: 1400,
    speed: 4800,
    speedMach: 14,
    altitude: 150000,
    warhead: '450 kg HE maniobrable',
    guidance: 'INS + GPS + terminal IR',
    length: 13.5, diameter: 1.0,
    launchPlatform: ['TEL terrestre'],
    CEP: 30,
    inService: 2023,
    status: 'active',
    uses: 'Primer misil hipersónico iraní. Presentado junio 2023. Maniobra con planeador independiente. No confirmada su eficacia real.',
    color: '#FF8C00',
    tags: ['hipersónico', 'nuevo', 'no-verificado'],
  },
  {
    id: 'IR-Shahed136',
    name: 'Shahed-136',
    natoCode: 'Geran-2 (Rusia)',
    country: 'iran', flag: '🇮🇷',
    type: 'cruise',
    range: 1900,
    speed: 55, // m/s
    speedMach: 0.16,
    altitude: 150,
    warhead: '30–50 kg HE',
    guidance: 'INS + GLONASS + Optical matching',
    length: 3.5, diameter: 0.2,
    launchPlatform: ['Lanzador rampa 6 tubos', 'Camión'],
    CEP: 15,
    inService: 2021,
    status: 'active',
    uses: 'Dron-kamikaze / misil de crucero lento. Fabricado en masa. Más de 2.000 usados en Ucrania por Rusia. Alta saturación.',
    color: '#FF8C00',
    tags: ['dron-kamikaze', 'barato', 'saturación', 'Ucrania'],
  },

  // ── ISRAEL ───────────────────────────────
  {
    id: 'IL-Jericho3',
    name: 'Jericho III',
    natoCode: '—',
    country: 'israel', flag: '🇮🇱',
    type: 'ballistic',
    range: 11500,
    speed: 6500,
    speedMach: 19,
    altitude: 1000000,
    warhead: 'Nuclear estimado 750kt–1MT (no confirmado)',
    guidance: 'INS + astro-inercial',
    length: 15.5, diameter: 1.56,
    launchPlatform: ['Silo subterráneo'],
    CEP: 30,
    inService: 2011,
    status: 'active',
    uses: 'Disuasor nuclear estratégico israelí. Parte de la política de ambigüedad nuclear. Alcance global.',
    color: '#39FF14',
    tags: ['ICBM', 'nuclear-implícito', 'disuasión', 'SSBN'],
  },
  {
    id: 'IL-DelilahAL',
    name: 'Delilah AL',
    natoCode: '—',
    country: 'israel', flag: '🇮🇱',
    type: 'cruise',
    range: 250,
    speed: 200,
    speedMach: 0.58,
    altitude: 50,
    warhead: '30 kg HE penetrador',
    guidance: 'INS + GPS + IIR + datalink tiempo real',
    length: 2.7, diameter: 0.33,
    launchPlatform: ['F-16I', 'F-15I', 'F-35I Adir'],
    CEP: 1,
    inService: 2003,
    status: 'active',
    uses: 'Misil de loitering inteligente. Capacidad de abortar y re-atacar. Usado en múltiples conflictos en Medio Oriente.',
    color: '#39FF14',
    tags: ['loitering', 'precisión', 'F-35', 'reconocimiento'],
  },
];

// Conflict zones for simulation
const CONFLICT_ZONES = {
  ukraine: {
    name: 'UCRANIA',
    launches: [
      { name: 'Belgorod (RU)', lat: 50.6, lon: 36.6 },
      { name: 'Crimea (RU)', lat: 45.0, lon: 34.0 },
      { name: 'Voronezh (RU)', lat: 51.67, lon: 39.18 },
      { name: 'Krasnodar (RU)', lat: 45.04, lon: 38.98 },
    ],
    targets: [
      { name: 'Kyiv', lat: 50.45, lon: 30.52 },
      { name: 'Kharkiv', lat: 49.99, lon: 36.23 },
      { name: 'Zaporizhzhia', lat: 47.84, lon: 35.14 },
      { name: 'Odesa', lat: 46.48, lon: 30.73 },
      { name: 'Dnipro', lat: 48.46, lon: 35.04 },
      { name: 'Mykolaiv', lat: 46.97, lon: 32.0 },
      { name: 'Sumy', lat: 50.91, lon: 34.80 },
      { name: 'Poltava', lat: 49.59, lon: 34.55 },
      { name: 'Kryvyi Rih', lat: 47.91, lon: 33.39 },
    ],
    systems: ['R-Kalibr', 'R-Iskander', 'R-Kh101', 'IR-Shahed136'],
    weight: 0.35,
    active: true,
  },
  middleEast: {
    name: 'MEDIO ORIENTE',
    launches: [
      { name: 'S. Líbano (Hezbolá)', lat: 33.3, lon: 35.5 },
      { name: 'Gaza (Hamas)', lat: 31.35, lon: 34.3 },
      { name: 'Yemen (Houthi)', lat: 15.55, lon: 44.2 },
      { name: 'Irán (Tabriz)', lat: 38.1, lon: 46.3 },
      { name: 'Siria (Latakia)', lat: 35.54, lon: 35.79 },
    ],
    targets: [
      { name: 'Tel Aviv', lat: 32.07, lon: 34.78 },
      { name: 'Haifa', lat: 32.82, lon: 35.0 },
      { name: 'Ashkelon', lat: 31.67, lon: 34.57 },
      { name: 'Eilat', lat: 29.56, lon: 34.95 },
      { name: 'Riyadh', lat: 24.69, lon: 46.72 },
      { name: 'Aden', lat: 12.78, lon: 45.04 },
      { name: 'Jeddah', lat: 21.48, lon: 39.18 },
    ],
    systems: ['IR-Shahab3', 'IR-Fattah', 'IR-Shahed136'],
    weight: 0.35,
    active: true,
  },
  southChinaSea: {
    name: 'MAR DEL SUR DE CHINA',
    launches: [
      { name: 'Fujian (CN)', lat: 26.09, lon: 119.30 },
      { name: 'Hainan (CN)', lat: 20.03, lon: 110.35 },
      { name: 'Guangdong (CN)', lat: 23.12, lon: 113.26 },
    ],
    targets: [
      { name: 'Estrecho de Taiwán', lat: 24.5, lon: 120.0 },
      { name: 'Taipei', lat: 25.04, lon: 121.56 },
      { name: 'Islas Spratly', lat: 9.5, lon: 114.5 },
      { name: 'Islas Paracel', lat: 16.5, lon: 112.0 },
    ],
    systems: ['CN-DF21D', 'CN-DF17', 'CN-YJ18'],
    weight: 0.15,
    active: true,
  },
  northKorea: {
    name: 'COREA DEL NORTE',
    launches: [
      { name: 'Pyongyang', lat: 39.03, lon: 125.75 },
      { name: 'Sinpo (submarin)', lat: 40.02, lon: 128.19 },
      { name: 'Sunan', lat: 39.19, lon: 125.69 },
    ],
    targets: [
      { name: 'Mar de Japón', lat: 37.5, lon: 132.0 },
      { name: 'Pacífico Oriental', lat: 35.0, lon: 140.0 },
      { name: 'Seúl', lat: 37.56, lon: 126.97 },
      { name: 'Tokio', lat: 35.69, lon: 139.69 },
    ],
    systems: ['NK-Hwasong17', 'NK-Hwasong15', 'NK-KN23'],
    weight: 0.10,
    active: true,
  },
  sahel: {
    name: 'SAHEL / ÁFRICA OCC.',
    launches: [
      { name: 'Mali (Bamako)', lat: 12.65, lon: -8.0 },
      { name: 'Burkina Faso', lat: 12.36, lon: -1.53 },
      { name: 'Níger', lat: 13.52, lon: 2.11 },
    ],
    targets: [
      { name: 'Gao (Mali)', lat: 16.27, lon: -0.04 },
      { name: 'Timbuktu', lat: 16.77, lon: -3.0 },
      { name: 'Agadez', lat: 16.98, lon: 7.99 },
    ],
    systems: ['R-Kalibr', 'IR-Shahed136'],
    weight: 0.05,
    active: true,
  },
};

// GDACS disaster type mapping
const GDACS_TYPE_MAP = {
  EQ: 'earthquake', TC: 'storm', FL: 'flood', DR: 'drought',
  VO: 'volcano', WF: 'wildfire', LS: 'landslide',
};

// Severity levels
const SEV = {
  CRITICAL: { label: 'CRÍTICO', color: '#FF2040', weight: 10, order: 4 },
  HIGH:     { label: 'ALTO',    color: '#FF8C00', weight: 6,  order: 3 },
  MEDIUM:   { label: 'MEDIO',   color: '#F5E642', weight: 3,  order: 2 },
  LOW:      { label: 'BAJO',    color: '#39FF14', weight: 1,  order: 1 },
};

function getMissileData(id) {
  return MISSILE_DB.find(m => m.id === id);
}

function getRandomItem(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}
